# Theme settings
doks:
    baseurl: "https://mrazomej.github.io/phd/"
    color_theme:  grey # Available themes: blue (default), green, purple, red, and yellow
    header:
        logo:
            text: Manuel Razo-Mejia | PhD Thesis
            image:
    footer:
        content:
            logo:
                text: Manuel Razo-Mejia | PhD Thesis
                image:
            copyright: Copyright &copy; 2021. - Manuel Razo-Mejia <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/mrazomej'
    google_analytics:
        tracking_code: UA-109526846-4 
    comments:
        disqus_forum_shortname: mrazomej-phd # Add your disqus forum shortname

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
jekyll_get:
  - data: github
    json: 'https://api.github.com/orgs/gchure/repos'
    cache: false

exclude: [ 'README.md', 'CHANGELOG.md', 'src/data/', 
           'vendor', 'phd', 'phd.egg-info', 'dst', 'vscode', '.bundle',
           '.jekyll-cache', '_plugins', '*.lua','*.pdf','*.svg','src/*/code',
           '*.py', '*.tex', '*.sh', 'Gemfile', '*.lock', 'Makefile',
           'presentation/']
permalink: /:title/
gems:
  - jekyll-numbered-headings
  - jekyll-pandoc-multiple-formats
  - jekyll-pandoc

markdown: Pandoc
pandoc:
    extensions:
      - mathjax
    skip:
      full: false
      posts: false
      categories: false     
    flags: >
      --default-image-extension=.png
      --dpi 300
      --filter pandoc-crossref
      --citeproc
      --bibliography=src/references.bib
      --csl=src/styles/cell.csl
      --metadata link-citations

# scholar:
#   style: apa
#   locale: en

#   sort_by: none
#   order: ascending

#   source: ./src/
#   bibliography: references.bib
#   bibliography_template: "{{reference}}"

#   replace_strings: true
#   join_strings:    true

#   details_dir:    bibliography
#   details_layout: bibtex.html
#   details_link:   Details

#   query: "@*"
---
